# Generated by Django 2.2.5 on 2021-02-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_topic_topic_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.CharField(default='No description', max_length=300),
        ),
    ]
